### ISSUE TITLE
[Feature]: アイコン作成

### ISSUE THREAD

**Issue by keigomichi** [keigomichi/tsundoku#1]
### リクエストの内容

- アプリのアイコンを作成する。
- 本がスタックされたキャラクター（イメージ）

### Todo

- [ ]

**Comment by kototo522** [comment]
<img width="588" alt="スクリーンショット 2023-06-09 23 58 53" src="https://github.com/keigomichi/tsundoku/assets/72599621/c1cd984e-b5e0-4329-a7c3-ab90aeb50852">
